[package]
name = "echran"
version = "0.1.0"
authors = ["Chad Baxter <cbaxter@mail.umw.edu>"]

[dependencies]
clap = "2.19.1"
ears = "0.3.5"
hex = "0.2.0"
rand = "*"
tempfile = "2.1.4"
#apt-get install libopenal-dev libsndfile1-dev
